name = "streaming-assistant"
compatibility_date = "2024-01-01"

# Pages configuration
pages_build_output_dir = "dist"

# Build configuration
[build]
command = "npm run build"
cwd = "."
watch_dir = "src"
