name = "streaming-assistant"
compatibility_date = "2024-01-01"

# Pages configuration
pages_build_output_dir = "dist"

# Worker configuration
main = "src/worker.js"

# Static assets configuration
[site]
bucket = "./dist"
entry-point = "workers-site"

# Build configuration
[build]
command = "npm run build"
cwd = "."
watch_dir = "src"
